[package]
name = "nolox"
version = "0.1.0"
authors = ["Damir Shaikhutdinov <lost404@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
