name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install and select nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, rust-src, llvm-tools-preview
    - name: Build cargo-xbuild
      run: cargo install cargo-xbuild
    - name: Build cargo-bootimage
      run: cargo install bootimage
    - name: Build
      run: cargo bootimage
